-- Phần mềm quản lí bán hàng đơn giản - Howkteam 16/10/2021


CREATE DATABASE QUANLIBANHANG

USE QUANLIBANHANG

CREATE TABLE BAN
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	TENBAN NVARCHAR(50) NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL DEFAULT N'Trống',
)
GO
CREATE TABLE TAIKHOAN
(
	TK NVARCHAR(50) NOT NULL PRIMARY KEY,
	MK NVARCHAR(50) NOT NULL,
	TENDN NVARCHAR(50) NOT NULL,
	LOAITK INT NOT NULL
)
GO
CREATE TABLE LOAISP
(	
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
)

GO
CREATE TABLE SANPHAM
(	
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	IDLSP INT NOT NULL,
	DONGIA FLOAT NOT NULL DEFAULT 0
	
	FOREIGN KEY (IDLSP) REFERENCES LOAISP(ID),
)
CREATE TABLE HOADON
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	IDBAN INT NOT NULL,
	NGAYDEN DATE NOT NULL DEFAULT GETDATE(),
	NGAYDI DATE ,
	TRANGTHAI INT NOT NULL DEFAULT 0 -- THANH TOAN HAY CHUA 1/0
	
	FOREIGN KEY (IDBAN) REFERENCES BAN(ID),
)
GO
CREATE TABLE CHITIETHOADON
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,	
	IDHOADON INT NOT NULL,
	IDSP INT NOT NULL,
	SL INT NOT NULL DEFAULT 0

	FOREIGN KEY (IDHOADON) REFERENCES HOADON(ID),
	FOREIGN KEY (IDSP) REFERENCES SANPHAM(ID),
)



INSERT TAIKHOAN VALUES('tamnguyen662001','662001',N'Tâm Nguyễn',1)
INSERT TAIKHOAN VALUES('duynguyen442001','123123',N'Duy Nguyễn',0)
INSERT TAIKHOAN VALUES('namtran632002','321123',N'Nam Trần',0)
INSERT TAIKHOAN VALUES('tringuyen2000','111111',N'Trí Nguyễn',0)
INSERT TAIKHOAN VALUES('t','1',N'Admin',0)


INSERT LOAISP VALUES (N'Cà phê')
INSERT LOAISP VALUES (N'Trà')
INSERT LOAISP VALUES (N'Nước ép')
INSERT LOAISP VALUES (N'Cocktail')
INSERT LOAISP VALUES (N'Đá xay')


INSERT SANPHAM VALUES (N'Cà phê nguyên chất',7,18000)
INSERT SANPHAM VALUES (N'Trà Ô long',8,20000)
INSERT SANPHAM VALUES (N'Cam vắt',9,22000)
INSERT SANPHAM VALUES (N'Cocktail Whiskey Sour',10,30000)
INSERT SANPHAM VALUES (N'Việt quất đá xay ',11,24000)


INSERT HOADON VALUES (20,GETDATE(),GETDATE(),1)
INSERT HOADON VALUES (21,'2/3/2021','2/3/2021',0)
INSERT HOADON VALUES (22,'6/6/2021','6/6/2021',0)
INSERT HOADON VALUES (23,GETDATE(),GETDATE(),1)
INSERT HOADON VALUES (24,GETDATE(),GETDATE(),1)
INSERT HOADON VALUES (26,'2/8/2021','2/8/2021',0)
INSERT HOADON VALUES (27,'6/6/2021','6/4/2021',0)
INSERT HOADON VALUES (28,'11/7/2021','11/7/2021',0)
INSERT HOADON VALUES (29,'12/6/2021','12/6/2021',0)



INSERT CHITIETHOADON VALUES (1,1,3)
INSERT CHITIETHOADON VALUES (2,2,4)
INSERT CHITIETHOADON VALUES (3,3,3)
INSERT CHITIETHOADON VALUES (4,4,2)
INSERT CHITIETHOADON VALUES (5,5,6)
INSERT CHITIETHOADON VALUES (1002,5,6)
INSERT CHITIETHOADON VALUES (1003,5,6)
INSERT CHITIETHOADON VALUES (1004,5,3)
INSERT CHITIETHOADON VALUES (1005,4,4)
INSERT CHITIETHOADON VALUES (1006,5,5)
INSERT CHITIETHOADON VALUES (1007,3,6)
INSERT CHITIETHOADON VALUES (1008,2,1)
INSERT CHITIETHOADON VALUES (1009,1,3)
INSERT CHITIETHOADON VALUES (1010,5,2)


SELECT * FROM CHITIETHOADON
SELECT * FROM HOADON
select * from BAN



DECLARE @I INT = 10
WHILE @I < 18
BEGIN
	INSERT BAN (TENBAN) VALUES(N'Bàn '+ CAST(@I AS NVARCHAR(50)))
	SET @I = @I+1
END

UPDATE BAN SET TRANGTHAI = N'Đã đặt' WHERE ID = 26

GO
CREATE PROC DSBAN
AS
BEGIN
	SELECT * FROM BAN 
END
GO
EXEC DSBAN
delete 
from BAN where ID = '36'

GO
-- tạo procedure 
CREATE PROC DSTK
@TENDN NVARCHAR(50)
AS
BEGIN
		SELECT * FROM TAIKHOAN WHERE TENDN = @TENDN
END

EXEC DSTK N'Tâm Nguyễn'

GO

CREATE PROC LOGIN
@TK NVARCHAR(50),@MK NVARCHAR(50)
AS
BEGIN
	SELECT * FROM TAIKHOAN WHERE TK = @TK AND MK = @MK
END
GO


--EXEC LOGIN @TK , @MK
drop proc Login
SELECT * FROM TAIKHOAN WHERE TK = N't' AND MK = '1' 
SELECT * FROM TAIKHOAN WHERE TK = N'' OR 1=1

SELECT * FROM HOADON WHERE  IDBAN = 25 AND TRANGTHAI = 0